name: Suggestion
description: Suggest additions to content, practice problems, or website appearance.
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to write a suggestion!

  - type: textarea
    id: topic
    attributes:
      label: What topic is your feature request on? Is it already in the table of contents?
      placeholder: The name of the topic in question, and a description if it is not already in the materials. Ex. Goto is not in the table of contents.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like. Is it new content, further description, more elaborate practice problems?
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: origin
    attributes:
      label: Describe the origin of this idea. Did it come from an online resource, from a lecture, or some other reachable source?
      description: We all have good ideas or need a better explanation sometimes. Ex. Dr. Whowuzit showed us this very nice example problem that would be great for the problem set.
      placeholder: The name of the source material, if there is any.

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here. Some professors may not want you sharing their examples online, and we want to respect that. Links to webpages that had content you want added can be put here, though.

  - type: checkboxes
    id: agreement
    attributes:
      label: Agreement
      description: By submitting this issue, you agree to act respectfully and follow common sense behavior.
      options:
        - label: I agree to these terms
          required: true
