name: Check

on:
  pull_request:

  # Allows you to call this workflow manually
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
          components: trunk

    - name: Build
      run: cargo build --verbose

    - name: Run cargo fmt
      run: cargo fmt -- --check

    - name: Run clippy
      run: cargo clippy

    - name: Run tests
      run: cargo test --verbose
