name: Check

on:
  pull_request:

  # Allows you to call this workflow manually
  workflow_dispatch:
  workflow_call:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --verbose

    - name: Run cargo fmt
      run: cargo fmt -- --check

    - name: Install clippy
      run: rustup component add clippy

    - name: Run clippy
      run: cargo clippy

    - name: Run tests
      run: cargo test --verbose
